### ISSUE TITLE
Links to Galaxy Zoo 2 tables on S3 are broken

### ISSUE THREAD

**Issue by willettk** [zooniverse/data.galaxyzoo.org#23]
A colleague tried to access the Galaxy Zoo 2 full data tables stored on S3, but all of them are yielding an "Access Denied" error message. This applies only to the Galaxy Zoo 2 full catalogs; all of the links to the other GZ1 and ancillary data still work. 

Eg: http://zooniverse-data.s3.amazonaws.com/galaxy-zoo-2/zoo2MainSpecz.csv.gz

*This XML file does not appear to have any style information associated with it. The document tree is shown below.*
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>A85A0D7720BC796F</RequestId>
<HostId>
6MLbcLnZRyrKPJ3BdfQ0BEkHpYaONKSegrFRqmzbX1WwzES1+StIXvm10uiTJXUjKUvWQEtuS1M=
</HostId>
</Error>
```

**Comment by astopy** [comment]
Oops, I've been archiving old data from S3 to Glacier to reduce storage costs. I didn't realise this one was still being used. It'll be back up tomorrow.

**Comment by willettk** [comment]
Thanks, Adam. The idea is for everything on this page to be the permanent public go-to for GZ data. If storage costs are too high, then you and Chris and I should chat about other options.

**Comment by astopy** [comment]
The files should all be back up now.

It's no problem to keep storing them. It's just that the zooniverse-data bucket wasn't particularly well organised, so it wasn't clear what was still being used.

**Comment by DarrenMcRoy** [comment]
Thanks, @astopy. This also got the archived Galaxy Zoo forum back up. Appreciate it!
